# Generated by Django 6.1.1 on 2026-10-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('primary', 'color_primary'), ('success', 'color_success'), ('warning', 'color_warning'), ('danger', 'color_danger'), ('info', 'color_info'), ('light', 'color_light')], default='primary', max_length=20, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('mdi-tag', 'icon_other'), ('mdi-cart', 'icon_shopping'), ('mdi-home', 'icon_housing'), ('mdi-car', 'icon_transport'), ('mdi-medical-bag', 'icon_health'), ('mdi-silverware-fork-knife', 'icon_food'), ('mdi-gift-outline', 'icon_gift'), ('mdi-cash', 'icon_salary'), ('mdi-piggy-bank-outline', 'icon_savings'), ('mdi-dumbbell', 'icon_leisure')], default='mdi-tag', max_length=50, verbose_name='icon'),
        ),
    ]
