# Generated by Django 6.1.1 on 2026-10-02 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_category_color_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='date'),
        ),
    ]
