# Generated by Django 6.1.1 on 2026-10-03 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_transfer',
            field=models.BooleanField(default=False, verbose_name='is_transfer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='linked_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.transaction', verbose_name='linked_transaction'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('mdi-tag', 'icon_other'), ('mdi-cart', 'icon_shopping'), ('mdi-home', 'icon_housing'), ('mdi-car', 'icon_transport'), ('mdi-medical-bag', 'icon_health'), ('mdi-silverware-fork-knife', 'icon_food'), ('mdi-gift-outline', 'icon_gift'), ('mdi-cash', 'icon_salary'), ('mdi-piggy-bank-outline', 'icon_savings'), ('mdi-dumbbell', 'icon_leisure'), ('mdi-school-outline', 'icon_education'), ('mdi-toolbox-outline', 'icon_services'), ('mdi-shield-check-outline', 'icon_insurance'), ('mdi-receipt-text-outline', 'icon_taxes'), ('mdi-airplane', 'icon_travel'), ('mdi-hanger', 'icon_clothing'), ('mdi-bank-transfer', 'icon_transfer')], default='mdi-tag', max_length=50, verbose_name='icon'),
        ),
    ]
