# Generated by Django 6.1.1 on 2026-10-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'theme_light'), ('dark', 'theme_dark')], default='light', max_length=10, verbose_name='theme_preference'),
        ),
    ]
